return {
  lsp_config = {
    mode = 'symbol_text',
    max_width = 20,
    symbol_map = {
      Array = '',
      Boolean = '⊨',
      Class = 'ﴯ',
      Color = '',
      Constant = '',
      Constructor = '',
      Enum = '',
      EnumMember = '',
      Event = '',
      Field = '',
      File = '',
      Folder = '',
      Function = '',
      Interface = 'ﰮ',
      Key = '',
      Keyword = '',
      Method = '',
      Module = '',
      Namespace = '',
      NONE = '',
      Null = 'NULL',
      Number = '',
      Object = '',
      Operator = '',
      Package = '',
      Property = '',
      Reference = '',
      Snippet = '',
      String = '',
      Struct = 'פּ',
      Text = '',
      TypeParameter = '',
      Unit = '',
      Value = '',
      Variable = '',
    },
    menu = {
      nvim_lsp = '[LSP]',
      emoji = '[Emoji]',
      path = '[Path]',
      calc = '[Calc]',
      cmp_tabnine = '[Tabnine]',
      vsnip = '[Snippet]',
      luasnip = '[Snippet]',
      buffer = '[Buffer]',
      tmux = '[TMUX]',
      copilot = '[Copilot]',
      treesitter = '[TreeSitter]',
      nvim_lua = '[Lua]',
      orgmode = '[Orgmode]',
    },
  },
  treesitter_ensure_installed = {
    'bash',
    'cmake',
    'cpp',
    'dockerfile',
    'fish',
    'go',
    'gomod',
    'help',
    'html',
    'java',
    'javascript',
    'json',
    'kotlin',
    'lua',
    'markdown',
    'markdown_inline',
    'nix',
    'org',
    'python',
    'regex',
    'sql',
    'typescript',
    'vim',
  },
}
